version: '3.8'

services:
  # Next.js Frontend Application (Development Mode)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_LIFF_ID=${NEXT_PUBLIC_LIFF_ID}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
